application: nyc-restaurant-grades
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /index\.html
  static_files: index.html
  upload: index.html

- url: /(goto)
  script: nyc_restaurant_grades.app

- url: /(home|find|updatesub)
  script: nyc_restaurant_grades.app
  login: required

- url: /(updateres|notify)
  script: nyc_restaurant_grades.app
  login: admin

libraries:
- name: jinja2
  version: latest
